const webpack = require("webpack");
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

const Paths = {
  src: path.join(__dirname, "../src"),
  dragDrop: path.join(__dirname, "../src/dragdrop.js"),
  styles: path.resolve(__dirname, "../src/styles"),
  dist: path.join(__dirname, "../dist"),
};

module.exports = {
  entry: {
    main: Paths.src,
    dragdrop: Paths.dragDrop,
  },
  output: {
    path: Paths.dist,
    filename: "[name].bundle.js",
    publicPath: "",
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: path.join(__dirname, "../index.html"),
    }),
  ],
  optimization: {
    runtimeChunk: "single",
  },
  resolve: {
    extensions: [".js", ".jsx", ".jsm"],
    alias: {
      styles: Paths.styles,
    },
  },
  mode: "development",
};
